export const FEATURES = {
  characters: 'characters',
  worldview: 'worldview',
  story: 'story',
  gallery: 'gallery',
  relationships: 'relationships',
  inbox: 'inbox',
  publicPage: 'publicPage',
  template: 'template',
  roster: 'roster',
  applications: 'applications',
  submissions: 'submissions',
  participants: 'participants',
  permissions: 'permissions',
} as const;

export const viewer = {
  id: 'user-wen',
  name: 'Wen',
  handle: 'yoi-studio',
  projectRoles: {
    'personal-archive': 'owner',
    'public-portfolio': 'owner',
    'private-collab': 'host',
    'open-collab': 'owner',
  },
};

export const projects = [
  {
    id: 'personal-archive',
    slug: 'personal-archive',
    name: '私人角色資料庫',
    workspaceKind: 'account_collection',
    color: '#8a857c',
    preset: 'personal_organization',
    ownerId: 'user-wen',
    collaborationMode: 'solo',
    visibility: 'private',
    portalEnabled: false,
    joinPolicy: 'closed',
    submissionsEnabled: false,
    enabledFeatures: [
      FEATURES.characters,
      FEATURES.worldview,
      FEATURES.story,
      FEATURES.gallery,
      FEATURES.relationships,
      FEATURES.inbox,
    ],
    description: '只給自己整理設定、靈感、草稿與跨企劃角色用，不需要主持人或審核流程。',
  },
  {
    id: 'public-portfolio',
    slug: 'yoi-portfolio',
    name: '宵霧公開展示',
    workspaceKind: 'project',
    color: '#8fa3b0',
    preset: 'public_showcase',
    ownerId: 'user-wen',
    collaborationMode: 'solo',
    visibility: 'public',
    portalEnabled: true,
    joinPolicy: 'closed',
    submissionsEnabled: false,
    enabledFeatures: [
      FEATURES.characters,
      FEATURES.worldview,
      FEATURES.story,
      FEATURES.gallery,
      FEATURES.relationships,
      FEATURES.publicPage,
    ],
    description: '個人維護的公開作品集。可展示角色與世界觀，但沒有成員、投稿或名冊審核。',
  },
  {
    id: 'private-collab',
    slug: 'moon-room',
    name: '月蝕密室共創',
    workspaceKind: 'project',
    color: '#6b5b95',
    preset: 'private_collaboration',
    ownerId: 'user-friend',
    collaborationMode: 'collaborative',
    visibility: 'private',
    portalEnabled: false,
    joinPolicy: 'invite',
    submissionsEnabled: false,
    enabledFeatures: [
      FEATURES.characters,
      FEATURES.worldview,
      FEATURES.story,
      FEATURES.gallery,
      FEATURES.relationships,
      FEATURES.template,
      FEATURES.roster,
      FEATURES.applications,
      FEATURES.participants,
      FEATURES.permissions,
    ],
    description: '私人多人共創企劃。需要成員、模板與角色加入流程，但不對外公開。',
  },
  {
    id: 'open-collab',
    slug: 'tokoyo-open',
    name: '常夜國公開招募',
    workspaceKind: 'project',
    color: '#3b5e6b',
    preset: 'public_collaboration',
    ownerId: 'user-wen',
    collaborationMode: 'collaborative',
    visibility: 'public',
    portalEnabled: true,
    joinPolicy: 'application',
    submissionsEnabled: true,
    enabledFeatures: [
      FEATURES.characters,
      FEATURES.worldview,
      FEATURES.story,
      FEATURES.gallery,
      FEATURES.relationships,
      FEATURES.publicPage,
      FEATURES.template,
      FEATURES.roster,
      FEATURES.applications,
      FEATURES.submissions,
      FEATURES.participants,
      FEATURES.permissions,
    ],
    description: '公開招募型共創企劃。有公開頁、角色卡模板、審核中心與參與者管理。',
  },
] as const;

export const characters = [
  {
    id: 'char-yoi',
    ownerId: 'user-wen',
    slug: 'yoigiri',
    name: '宵霧',
    rom: 'YOIGIRI',
    species: '妖狐',
    visibility: 'private',
    tagline: '在無人的夜路替迷途者點一盞燈。',
  },
  {
    id: 'char-tomori',
    ownerId: 'user-wen',
    slug: 'tomori',
    name: '燈守',
    rom: 'TOMORI',
    species: '付喪神',
    visibility: 'unlisted',
    tagline: '舊燈成精，記得每一次被點亮的夜晚。',
  },
  {
    id: 'char-nozomi',
    ownerId: 'user-wen',
    slug: 'nozomi',
    name: '望',
    rom: 'NOZOMI',
    species: '人類',
    visibility: 'public',
    tagline: '雪夜被引路的旅人，多年後重回神社。',
  },
  {
    id: 'char-mika',
    ownerId: 'user-wen',
    slug: 'mika',
    name: '未花',
    rom: 'MIKA',
    species: '未定',
    visibility: 'private',
    tagline: '全域角色庫裡的孤立草稿，尚未放入任何企劃。',
  },
] as const;

export const projectCharacterLinks = [
  {
    id: 'link-yoi-personal',
    projectId: 'personal-archive',
    characterId: 'char-yoi',
    status: 'active',
    faction: '私人整理',
    projectRole: '主角',
    templateVersionId: null,
  },
  {
    id: 'link-tomori-portfolio',
    projectId: 'public-portfolio',
    characterId: 'char-tomori',
    status: 'published',
    faction: '公開展示',
    projectRole: '展示角色',
    templateVersionId: null,
  },
  {
    id: 'link-yoi-private-collab',
    projectId: 'private-collab',
    characterId: 'char-yoi',
    status: 'approved',
    faction: '夜巡',
    projectRole: '主持角色',
    templateVersionId: 'tpl-private-v1',
  },
  {
    id: 'link-nozomi-open',
    projectId: 'open-collab',
    characterId: 'char-nozomi',
    status: 'approved',
    faction: '旅人',
    projectRole: '參與角色',
    templateVersionId: 'tpl-open-v2',
  },
  {
    id: 'link-tomori-open',
    projectId: 'open-collab',
    characterId: 'char-tomori',
    status: 'pending',
    faction: '守燈人',
    projectRole: '待審核',
    templateVersionId: 'tpl-open-v2',
  },
] as const;
