name = "oc-tools-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "oc-tools-db-v2"
database_id = "18d3eb15-6c21-48f0-aa6a-d912de01eb25"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "oc-tools-media"

[[kv_namespaces]]
binding = "KV"
id = "2c05fc09df2c4619ba0531ba62e355ce"

[vars]
FRONTEND_URL = "https://oc-tools-8g5.pages.dev"
INVITE_LIMIT = "5"
INVITE_ADMIN_IDS = "b7848b7e-8476-418c-a96a-c55097e281f6"
APP_ENV = "production"

[dev]
port = 8787
